### ISSUE TITLE
Nothing happens after clicking on an ID

### ISSUE THREAD

**Issue by Halon2** [Jipok/TelegramRetranslator#2]
I get the lists of ID's, and a message that tells me to "Select target from a list", but when I select an ID from the list nothing happens.

**Comment by Jipok** [comment]
What version of python and telethon do you have?
Everything works for me with python 3.5 and telethon 1.16 without problems.
What is written in the console?

**Comment by Halon2** [comment]
> What version of python and telethon do you have?
> Everything works for me with python 3.5 and telethon 1.16 without problems.
> What is written in the console?

Python 3.8.5
Telethon 1.19.2 

I just used python3 forwarder.py to start the forwarder script
After I press enter this output follows:
`/telegram-chat-forward# python3 forwarder.py 
Traceback (most recent call last):
  File "forwarder.py", line 10, in <module>
    from settings import API_ID, API_HASH, forwards, get_forward, update_offset, STRING_SESSION
  File "/telegram-chat-forward/settings.py", line 2, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
`
